language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ocAa3z+P9JiMb7khpruMLyQ2+BfHh70mR4PYeJn+Ziuxbq/tVFrlrRJ5pU5heOXVl0YnILqo+itxUSAsdjhBA6rOErZ663Xe7aeoSIWUgLZr29GI2IhSEQQOhvmZoZyVLhJAXZ2s4D6Uo4FMS/OtmWLMutBVrvZsDP/Z77j3yfEA/NwsOLzlaKWl/cIbnqXFUxYcGwtvr7WaiXc94wvFdPQVKpCFdAx6EFAwVn9poofxIK/EDTAILSghzd+gpBSvRjV7X7RIVwn44WdT/IbybILM45J1/jQ7vlxqPICtSpU81bcd1AaV1xj7qt8tr+zIXdazAaIlpbBJyyDyKvERSk0oIofn34ZncvvhiQxfLmFSmeC85SFkm0jWjAmPVC9b0YQYwRHNai47GaAfLu1n2ZJvdRIrAqS6d1K1dP1GrxjzbFA3QpP2uCCQ1Q8h9RH4gtKyJIbj6pMDkYPocaLneU+xUIogSoxFd2E7ZTNqvL3djXjus9IYXu/l+GbudEpA9xfJSvl99mLmGAOjIyhOWWYG5G2YNr+k8eCReIYmhbXTrc/r9yOAT020TyOCYt+hTXdllsrrHJZIQIZNL+JWtwgyiJDGfbAp7z5FxzVzBsJW/xet8AbI6Hukhcu/KLxnffS8V/UUS42Y3Hv/syzgLRBSVr7w/L5SocVU0f/t9Ec=
  file:
    - 'hast-util-from-text.js'
    - 'hast-util-from-text.min.js'
  on:
    tags: true
